version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: bikovshanin/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: bikovshanin/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: bikovshanin/foodgram_gateway:latest
    volumes:
      - static:/static/
      - media:/app/media/
    ports:
      - 8000:80
    depends_on:
      - backend